baseURL = 'https://example.org/'
locale  = 'en-US'
title   = 'PyData Hugo Theme — Example Site'

[module]
  [[module.imports]]
    path = "github.com/saltstack/pydata-hugo-theme"

[menus]
  [[menus.main]]
    name    = 'Home'
    pageRef = '/'
    weight  = 10
  [[menus.main]]
    name    = 'About'
    pageRef = '/about'
    weight  = 20

[params]
  [params.logo]
    text = 'Example Site'
